// angular-test/src/app/app.component.ts
import {Component, VERSION} from '@angular/core';
import * as _ from "lodash";
import {ELEMENTS_INITIAL_STATE, ELEMENTS_OPTIONS, ELEMENTS_COLORS} from "../constants"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  state = {
    ngVersion: VERSION.full,
    isToggleOn: false, // On/Off state indicator
    step: 0, // Iteration step
    extradigits: '000',
    int: undefined, // Reference to setInterval()
    mockData: [], // Where the list of elements will be store
    secondsCounter: 0,
    elnumValue: ELEMENTS_INITIAL_STATE,
    elnumOptions: ELEMENTS_OPTIONS,
    timer: undefined
  };

  /* Here we manage switching from initial state to running state (and the way back) when the application starts to generate data */
  switchState() {
    let mockData = this.state.mockData;
    let extradigits = this.state.extradigits;
    let timer = this.state.timer;
    let step = this.state.step;
    let int = this.state.int;
    const isToggleOn = !this.state.isToggleOn;

    /* If the application is already running will gets stopped */
    if (int) {
      clearInterval(int);
      clearInterval(this.state.timer);
      int = undefined;
    } else {
      timer = setInterval(() => {
        this.state.secondsCounter += 1;
      }, 1000);
      /* If the application isn't running it starts to generate data */
      int = setInterval(() => {
        /*Checking elements limit*/
        if ((step * 10) >= this.state.elnumValue) {
          this.clear(false);
          return;
        }
        step++;
        extradigits = (step < 10) ? '00' : (step < 100) ? '0' : '';
        mockData = _.shuffle(_.range(step * 10).map((element, index) => {
          return {style: this.divStyle(), content: index};
        }));
        this.state = {
          ...this.state,
          step, mockData, isToggleOn, int, extradigits
        };
      }, 1);
    }

    this.state = {
      ...this.state, timer, isToggleOn, int
    };
  }

  divStyle() {
    function ramdonColor() {
      return _.shuffle(ELEMENTS_COLORS)[0];
    }

    return {color: ramdonColor(), 'background-color': ramdonColor()};
  }

  setElnumValue(elnumValue) {
    this.clear(true);
    this.state.elnumValue = elnumValue;
  }

  /* Go back to initial state */
  clear(manual) {
    clearInterval(this.state.timer);
    if (this.state.int) {
      clearInterval(this.state.int);
    }
    if (manual) {
      this.state = {
        ...this.state,
        extradigits: '000',
        step: 0,
        mockData: [],
        secondsCounter: 0
      };
    }
    this.state = {
      ...this.state,
      isToggleOn: false,
      int: undefined
    };
  }

}

<div class="App">
  <div class="App-intro content">
    <div [ngStyle]="item.style" *ngFor="let item of state.mockData">
      {{item.content}}
    </div>
  </div>

  <div class="modal-container">
    <div class="modal-head">
      <div class="controls">
        <button (click)="switchState()" [class.active]="state.isToggleOn" [class.no-active]="!state.isToggleOn" >
          {{ state.isToggleOn ? 'STOP' : 'START' }}
        </button>
        <button (click)="clear(true)">
          CLEAR
        </button>
      </div>
      <div class="logo">
        <h5 class="App-title">
          <img alt="Angular Logo"
               src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
          Angular
          <small>(v.{{state.ngVersion}})</small>
        </h5>
      </div>
    </div>
    <div class="modal-content">
      <div class="content">
        <div class="counter elements">
          <p>{{state.extradigits + state.step * 10}}</p>
          <small>elements</small>
        </div>
        <div class="counter time">
          <p> {{((state.secondsCounter < 10) ? "0" : "") + state.secondsCounter}}</p>
          <small>seconds</small>
        </div>
      </div>
    </div>
    <div class="modal-foot">
      <button (click)="setElnumValue(elnum)" [class.active]="elnum === state.elnumValue"
              *ngFor="let elnum of state.elnumOptions">
        {{elnum}}
      </button>
    </div>
    <div class="info">
      <a target="_blank" class="social github-icon" href="https://github.com/acamposruiz/jsTestsByGamming/blob/master/angular-test/src/app/app.component.ts">
        <img class="img-social" alt="Github" src="assets/scalableVectorGraphics/github-icon.svg"/> <span>View source code</span>
      </a>
    </div>
  </div>
  <div class="back-container">
    <a title="Go back" class="back-link" href="https://acamposruiz.github.io/jsTestsByGamming/builds/home/index.html">
      <img class="img-social" alt="Go back" src="assets/scalableVectorGraphics/back.svg"/>
    </a>
  </div>
</div>

// react-test/src/AppComponent.js
import React from 'react';
import logo from './logo.svg';
import logoGithub from './github-icon.svg';
import backIcon from './back.svg';

const REACT_VERSION = React.version;

export function AppComponent({
                        items,
                        controls,
                        result,
                        selectMaxItems
}) {
  return (
    <div className="App">
      <div className="App-intro content">
        {items}
      </div>
      <div className="modal-container">
        <div className="modal-head">
          <div className="controls">
            {controls.toggleButton}
            {controls.clearButton}
          </div>
          <div className="logo">
            <h5 className="App-title">
              <img src={logo} className="App-logo" alt="logo"/>
              React <small>(v.{REACT_VERSION})</small>
            </h5>
          </div>
        </div>
        <div className="modal-content">
          <div className="content">
            <div className="counter elements">
              <p>{result.elements}</p>
              <small>elements</small>
            </div>
            <div className="counter time">
              <p>{result.time}</p>
              <small>seconds</small>
            </div>
          </div>
        </div>
        <div className="modal-foot">
          {selectMaxItems}
        </div>
        <div className="info">
          <a target="_blank" className="social github-icon" href="https://github.com/acamposruiz/jsTestsByGamming/blob/master/react-test/src/App.js">
            <img className="img-social" alt="Github" src={logoGithub}/> <span>View source code</span>
          </a>
        </div>
      </div>
      <div className="back-container">
        <a title="Go back" className="back-link" href="https://acamposruiz.github.io/jsTestsByGamming/builds/home/index.html">
          <img className="img-social" alt="Github" src={backIcon}/>
        </a>
      </div>
    </div>
  )
}
